spring:
  datasource:
    url: jdbc:mariadb://localhost:43306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: a1234
  thymeleaf:
    cache: false

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: imyh417@gmail.com
    password: tvgismstadpmogvk
    properties:
      mail:
        smtp:
          starttls:
            enable: true

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
